<template>
    <div>{{ value }}</div>
    <div class="outer">
        <div>
            <el-row>
                <div>{{ startNode || "未选择起点" }}</div>
                <el-button @click="function () { selectStartNodeTask.start() }">
                    {{ selectStartNodeTask.triggered ?
                        "起点选择中" : "选择起点" }}
                </el-button>
            </el-row>
            <el-row>
                <div>起点节点类型：{{ }}</div>
            </el-row>
            <el-row>
                <div>{{ endNode || "未选择终点" }}</div>
                <el-button @click="function () { selectEndNodeTask.start() }">
                    {{ selectEndNodeTask.triggered ?
                        "终点选择中" : "选择终点" }}
                </el-button>
            </el-row>
        </div>
        <div v-html="svgContent" id="graph-view"></div>
    </div>
</template>
<style>
.outer {
    width: 100%;
    display: flex;
    flex-direction: row;
}
</style>

<script setup lang="ts">
import { NodeTypes, parseNodeText } from "./nodetypes.ts"
import { onBeforeMount, onMounted, ref } from "vue"
class SelectionTask {
    public triggered = false
    private onSelected: (string) => void
    constructor(onSelected) {
        this.triggered = false
        this.onSelected = onSelected
    }
    start() {
        this.triggered = true
    }
    end(arg: string) {
        this.triggered = false
        this.onSelected(arg)
    }
}
const value = ref(1)


const startNode = ref("")
const selectStartNodeTask = ref(new SelectionTask((nodeID) => {
    startNode.value = nodesMap[nodeID]
}))

const endNode = ref("")
const selectEndNodeTask = ref(new SelectionTask((nodeID) => {
    endNode.value = "#" + nodeID
}))

let nodesMap = {}
const onClickNode = (nodeID: string, node: SVGElement) => {
    console.log(nodeID, node)
    for (const task of [selectStartNodeTask, selectEndNodeTask]) {
        if (task.value.triggered) {
            task.value.end(nodeID)
        }
    }
}
const queryNodeInfo = (node: SVGElement): { id: string, text: string } => {
    const idOnDOM: SVGTitleElement = node.querySelector("title") as any
    if (!idOnDOM) {
        throw Error("DOM节点没有title子标签" + `${node}`)
    }
    const text: SVGTextElement = node.querySelector("text") as any
    return { id: idOnDOM.innerHTML, text: text.innerHTML }
}

onMounted(() => {
    const divElement: HTMLDivElement = document.getElementById("graph-view") as HTMLDivElement
    const nodes: SVGElement[] = divElement.querySelectorAll(".node") as any
    nodesMap = {}
    for (const node of nodes) {
        const nodeInfo = queryNodeInfo(node)
        // console.log("发现节点#", nodeInfo.id, "ellipse", node.querySelector("ellipse"))
        node.querySelector("ellipse")!.setAttribute("fill", "white")
        console.log(nodeInfo.text, parseNodeText(nodeInfo.text))
        if (nodeInfo.text.startsWith("(&lt;operator&gt;.assignment")) {
            node.querySelector("ellipse")!.setAttribute("stroke", "#bb3333")
            node.querySelector("ellipse")!.setAttribute("stroke-width", "2px")
        } else if (!nodeInfo.text.startsWith("(&lt;operator&gt;")) {
            node.querySelector("ellipse")!.setAttribute("stroke", "#bbbb00")
            node.querySelector("ellipse")!.setAttribute("stroke-width", "2px")
        }
        // node.querySelector("ellipse")!.addEventListener("click", () => { onClickNode(nodeID, node) }, true);
        node.addEventListener("click", () => { onClickNode(nodeInfo.id, node) }, true);
        nodesMap[nodeInfo.id] = nodeInfo
    }
    // window.addEventListener('mouseup', (e: MouseEvent) => {
    //     console.log(e)
    //     // 在 #000000 和 #FFFFFF 之间随机选取一个颜色
    //     // const color = Math.round(Math.random() * 0xFFFFFF)

    //     // // 将 color 变量的值按照 CSS 的要求进行格式化
    //     // const fill = '#' + color.toString(16).padStart(6, '0')

    //     // // 将 color 变量设置的颜色应用到实际点击的元素上
    //     // e.target.style.fill = fill
    // })

})

const svgContent = `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz version 8.0.5 (20230430.1635)
 -->
<!-- Title: main Pages: 1 -->
<svg width="472pt" height="980pt"
 viewBox="0.00 0.00 472.40 980.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
<g id="graph0" class="graph" transform="scale(1 1) rotate(0) translate(4 976)">
<title>main</title>
<polygon fill="white" stroke="none" points="-4,4 -4,-976 468.4,-976 468.4,4 -4,4"/>
<!-- 18 -->
<g id="node1" class="node">
<title>18</title>
<ellipse fill="none" stroke="black" cx="232.2" cy="-810" rx="189.78" ry="18"/>
<text text-anchor="start" x="97.57" y="-805.58" font-family="Times New Roman,serif" font-size="14.00">(&lt;operator&gt;.assignment,signal = alloc_signal())</text>
<text text-anchor="start" x="360.82" y="-805.58" font-family="Times New Roman,serif" baseline-shift="sub" font-size="14.00">7</text>
</g>
<!-- 22 -->
<g id="node7" class="node">
<title>22</title>
<ellipse fill="none" stroke="black" cx="232.2" cy="-738" rx="130.9" ry="18"/>
<text text-anchor="start" x="141.82" y="-733.58" font-family="Times New Roman,serif" font-size="14.00">(&lt;operator&gt;.greaterThan,a &gt; 0)</text>
<text text-anchor="start" x="316.57" y="-733.58" font-family="Times New Roman,serif" baseline-shift="sub" font-size="14.00">8</text>
</g>
<!-- 18&#45;&gt;22 -->
<g id="edge1" class="edge">
<title>18&#45;&gt;22</title>
<path fill="none" stroke="black" d="M232.2,-791.7C232.2,-784.24 232.2,-775.32 232.2,-766.97"/>
<polygon fill="black" stroke="black" points="235.7,-767.1 232.2,-757.1 228.7,-767.1 235.7,-767.1"/>
</g>
<!-- 36 -->
<g id="node2" class="node">
<title>36</title>
<ellipse fill="none" stroke="black" cx="232.2" cy="-378" rx="232.2" ry="18"/>
<text text-anchor="start" x="65.7" y="-373.57" font-family="Times New Roman,serif" font-size="14.00">(&lt;operator&gt;.assignment,temperature = get_temperature())</text>
<text text-anchor="start" x="386.7" y="-373.57" font-family="Times New Roman,serif" baseline-shift="sub" font-size="14.00">18</text>
</g>
<!-- 41 -->
<g id="node10" class="node">
<title>41</title>
<ellipse fill="none" stroke="black" cx="232.2" cy="-306" rx="192.28" ry="18"/>
<text text-anchor="start" x="95.7" y="-301.57" font-family="Times New Roman,serif" font-size="14.00">(&lt;operator&gt;.multiplication,temperature * 1000)</text>
<text text-anchor="start" x="356.7" y="-301.57" font-family="Times New Roman,serif" baseline-shift="sub" font-size="14.00">19</text>
</g>
<!-- 36&#45;&gt;41 -->
<g id="edge2" class="edge">
<title>36&#45;&gt;41</title>
<path fill="none" stroke="black" d="M232.2,-359.7C232.2,-352.24 232.2,-343.32 232.2,-334.97"/>
<polygon fill="black" stroke="black" points="235.7,-335.1 232.2,-325.1 228.7,-335.1 235.7,-335.1"/>
</g>
<!-- 39 -->
<g id="node3" class="node">
<title>39</title>
<ellipse fill="none" stroke="black" cx="232.2" cy="-234" rx="217.23" ry="18"/>
<text text-anchor="start" x="76.95" y="-229.57" font-family="Times New Roman,serif" font-size="14.00">(&lt;operator&gt;.assignment,temp2 = temperature * 1000)</text>
<text text-anchor="start" x="375.45" y="-229.57" font-family="Times New Roman,serif" baseline-shift="sub" font-size="14.00">19</text>
</g>
<!-- 44 -->
<g id="node4" class="node">
<title>44</title>
<ellipse fill="none" stroke="black" cx="232.2" cy="-162" rx="198.27" ry="18"/>
<text text-anchor="start" x="91.2" y="-157.57" font-family="Times New Roman,serif" font-size="14.00">(use_temperature,use_temperature(temperature))</text>
<text text-anchor="start" x="361.2" y="-157.57" font-family="Times New Roman,serif" baseline-shift="sub" font-size="14.00">20</text>
</g>
<!-- 39&#45;&gt;44 -->
<g id="edge3" class="edge">
<title>39&#45;&gt;44</title>
<path fill="none" stroke="black" d="M232.2,-215.7C232.2,-208.24 232.2,-199.32 232.2,-190.97"/>
<polygon fill="black" stroke="black" points="235.7,-191.1 232.2,-181.1 228.7,-191.1 235.7,-191.1"/>
</g>
<!-- 46 -->
<g id="node5" class="node">
<title>46</title>
<ellipse fill="none" stroke="black" cx="232.2" cy="-90" rx="114.94" ry="18"/>
<text text-anchor="start" x="153.82" y="-85.58" font-family="Times New Roman,serif" font-size="14.00">(RETURN,return;,return;)</text>
<text text-anchor="start" x="298.57" y="-85.58" font-family="Times New Roman,serif" baseline-shift="sub" font-size="14.00">21</text>
</g>
<!-- 44&#45;&gt;46 -->
<g id="edge4" class="edge">
<title>44&#45;&gt;46</title>
<path fill="none" stroke="black" d="M232.2,-143.7C232.2,-136.24 232.2,-127.32 232.2,-118.97"/>
<polygon fill="black" stroke="black" points="235.7,-119.1 232.2,-109.1 228.7,-119.1 235.7,-119.1"/>
</g>
<!-- 47 -->
<g id="node14" class="node">
<title>47</title>
<ellipse fill="none" stroke="black" cx="232.2" cy="-18" rx="113.94" ry="18"/>
<text text-anchor="start" x="154.57" y="-13.57" font-family="Times New Roman,serif" font-size="14.00">(METHOD_RETURN,int)</text>
<text text-anchor="start" x="303.82" y="-13.57" font-family="Times New Roman,serif" baseline-shift="sub" font-size="14.00">5</text>
</g>
<!-- 46&#45;&gt;47 -->
<g id="edge5" class="edge">
<title>46&#45;&gt;47</title>
<path fill="none" stroke="black" d="M232.2,-71.7C232.2,-64.24 232.2,-55.32 232.2,-46.97"/>
<polygon fill="black" stroke="black" points="235.7,-47.1 232.2,-37.1 228.7,-47.1 235.7,-47.1"/>
</g>
<!-- 20 -->
<g id="node6" class="node">
<title>20</title>
<ellipse fill="none" stroke="black" cx="232.2" cy="-882" rx="115.93" ry="18"/>
<text text-anchor="start" x="153.07" y="-877.58" font-family="Times New Roman,serif" font-size="14.00">(alloc_signal,alloc_signal())</text>
<text text-anchor="start" x="305.32" y="-877.58" font-family="Times New Roman,serif" baseline-shift="sub" font-size="14.00">7</text>
</g>
<!-- 20&#45;&gt;18 -->
<g id="edge6" class="edge">
<title>20&#45;&gt;18</title>
<path fill="none" stroke="black" d="M232.2,-863.7C232.2,-856.24 232.2,-847.32 232.2,-838.97"/>
<polygon fill="black" stroke="black" points="235.7,-839.1 232.2,-829.1 228.7,-839.1 235.7,-839.1"/>
</g>
<!-- 29 -->
<g id="node8" class="node">
<title>29</title>
<ellipse fill="none" stroke="black" cx="232.2" cy="-594" rx="135.89" ry="18"/>
<text text-anchor="start" x="138.07" y="-589.58" font-family="Times New Roman,serif" font-size="14.00">(&lt;operator&gt;.greaterThan,b &gt; 0)</text>
<text text-anchor="start" x="314.32" y="-589.58" font-family="Times New Roman,serif" baseline-shift="sub" font-size="14.00">13</text>
</g>
<!-- 22&#45;&gt;29 -->
<g id="edge8" class="edge">
<title>22&#45;&gt;29</title>
<path fill="none" stroke="black" d="M203.02,-720.17C190.45,-711.2 177.07,-698.92 170.2,-684 163.5,-669.47 163.5,-662.53 170.2,-648 175.52,-636.46 184.72,-626.5 194.44,-618.43"/>
<polygon fill="black" stroke="black" points="196.23,-620.7 202.02,-611.83 191.96,-615.15 196.23,-620.7"/>
</g>
<!-- 26 -->
<g id="node11" class="node">
<title>26</title>
<ellipse fill="none" stroke="black" cx="313.2" cy="-666" rx="133.9" ry="18"/>
<text text-anchor="start" x="220.57" y="-661.58" font-family="Times New Roman,serif" font-size="14.00">(free_signal,free_signal(signal))</text>
<text text-anchor="start" x="393.82" y="-661.58" font-family="Times New Roman,serif" baseline-shift="sub" font-size="14.00">10</text>
</g>
<!-- 22&#45;&gt;26 -->
<g id="edge7" class="edge">
<title>22&#45;&gt;26</title>
<path fill="none" stroke="black" d="M251.81,-720.05C261.81,-711.41 274.15,-700.75 285.13,-691.26"/>
<polygon fill="black" stroke="black" points="286.93,-693.46 292.21,-684.28 282.35,-688.17 286.93,-693.46"/>
</g>
<!-- 38 -->
<g id="node9" class="node">
<title>38</title>
<ellipse fill="none" stroke="black" cx="232.2" cy="-450" rx="151.86" ry="18"/>
<text text-anchor="start" x="126.07" y="-445.57" font-family="Times New Roman,serif" font-size="14.00">(get_temperature,get_temperature())</text>
<text text-anchor="start" x="326.32" y="-445.57" font-family="Times New Roman,serif" baseline-shift="sub" font-size="14.00">18</text>
</g>
<!-- 29&#45;&gt;38 -->
<g id="edge10" class="edge">
<title>29&#45;&gt;38</title>
<path fill="none" stroke="black" d="M203.02,-576.17C190.45,-567.2 177.07,-554.92 170.2,-540 163.5,-525.47 163.5,-518.53 170.2,-504 175.47,-492.56 184.56,-482.67 194.18,-474.64"/>
<polygon fill="black" stroke="black" points="195.92,-476.95 201.69,-468.06 191.64,-471.41 195.92,-476.95"/>
</g>
<!-- 33 -->
<g id="node12" class="node">
<title>33</title>
<ellipse fill="none" stroke="black" cx="313.2" cy="-522" rx="133.9" ry="18"/>
<text text-anchor="start" x="220.57" y="-517.58" font-family="Times New Roman,serif" font-size="14.00">(free_signal,free_signal(signal))</text>
<text text-anchor="start" x="393.82" y="-517.58" font-family="Times New Roman,serif" baseline-shift="sub" font-size="14.00">15</text>
</g>
<!-- 29&#45;&gt;33 -->
<g id="edge9" class="edge">
<title>29&#45;&gt;33</title>
<path fill="none" stroke="black" d="M251.81,-576.05C261.81,-567.41 274.15,-556.75 285.13,-547.26"/>
<polygon fill="black" stroke="black" points="286.93,-549.46 292.21,-540.28 282.35,-544.17 286.93,-549.46"/>
</g>
<!-- 38&#45;&gt;36 -->
<g id="edge11" class="edge">
<title>38&#45;&gt;36</title>
<path fill="none" stroke="black" d="M232.2,-431.7C232.2,-424.24 232.2,-415.32 232.2,-406.97"/>
<polygon fill="black" stroke="black" points="235.7,-407.1 232.2,-397.1 228.7,-407.1 235.7,-407.1"/>
</g>
<!-- 41&#45;&gt;39 -->
<g id="edge12" class="edge">
<title>41&#45;&gt;39</title>
<path fill="none" stroke="black" d="M232.2,-287.7C232.2,-280.24 232.2,-271.32 232.2,-262.97"/>
<polygon fill="black" stroke="black" points="235.7,-263.1 232.2,-253.1 228.7,-263.1 235.7,-263.1"/>
</g>
<!-- 26&#45;&gt;29 -->
<g id="edge13" class="edge">
<title>26&#45;&gt;29</title>
<path fill="none" stroke="black" d="M293.59,-648.05C283.59,-639.41 271.25,-628.75 260.27,-619.26"/>
<polygon fill="black" stroke="black" points="263.04,-616.17 253.19,-612.28 258.47,-621.46 263.04,-616.17"/>
</g>
<!-- 33&#45;&gt;38 -->
<g id="edge14" class="edge">
<title>33&#45;&gt;38</title>
<path fill="none" stroke="black" d="M293.59,-504.05C283.59,-495.41 271.25,-484.75 260.27,-475.26"/>
<polygon fill="black" stroke="black" points="263.04,-472.17 253.19,-468.28 258.47,-477.46 263.04,-472.17"/>
</g>
<!-- 13 -->
<g id="node13" class="node">
<title>13</title>
<ellipse fill="none" stroke="black" cx="232.2" cy="-954" rx="80.01" ry="18"/>
<text text-anchor="start" x="180.07" y="-949.58" font-family="Times New Roman,serif" font-size="14.00">(METHOD,main)</text>
<text text-anchor="start" x="278.32" y="-949.58" font-family="Times New Roman,serif" baseline-shift="sub" font-size="14.00">5</text>
</g>
<!-- 13&#45;&gt;20 -->
<g id="edge15" class="edge">
<title>13&#45;&gt;20</title>
<path fill="none" stroke="black" d="M232.2,-935.7C232.2,-928.24 232.2,-919.32 232.2,-910.97"/>
<polygon fill="black" stroke="black" points="235.7,-911.1 232.2,-901.1 228.7,-911.1 235.7,-911.1"/>
</g>
</g>
</svg>

`



</script>